@rootURL = https://localhost:7287

GET {{rootURL}}/weatherforecast/
Accept: application/json

###
GET {{rootURL}}/api/books
Accept: application/json

###
GET {{rootURL}}/api/books/2
Accept: application/json

###
POST {{rootURL}}/api/books
Content-Type: application/json
{
  "title" : "C# Unlocked",
  "author" : "Stojance Oreskov",
  "yearPublished" : 2026
}

###
PUT {{rootURL}}/api/books/5
Content-Type: application/json
{
  "id" : 5,
  "title" : "Moby-Dick",
  "author" : "Stojance Oreskov",
  "yearPublished" : 1851
}

###
DELETE {{rootURL}}/api/books/3
